//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViatoremModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        public System.Guid SeatID { get; set; }
        public System.Guid BusID { get; set; }
        public System.Guid ScheduleID { get; set; }
        public System.Guid UserID { get; set; }
        public string SeatLoc { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual User User { get; set; }
    }
}
